# Generated by Django 5.1.1 on 2024-10-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='content',
            new_name='contents',
        ),
    ]
