# Generated by Django 5.1.1 on 2024-10-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_content_conversationmessage_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='created_At',
            new_name='created_by',
        ),
    ]
